/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */

#ifndef _CAM_IFE_CSID_662_H_
#define _CAM_IFE_CSID_662_H_

#include <linux/module.h>
#include "camera_main.h"
#include "cam_ife_csid_dev.h"
#include "cam_ife_csid_common.h"
#include "cam_ife_csid_hw_ver1.h"

static struct cam_ife_csid_ver1_path_reg_info
	cam_ife_csid_662_ipp_reg_info = {
		.irq_status_addr                  = 0x30,
		.irq_mask_addr                    = 0x34,
		.irq_clear_addr                   = 0x38,
		.irq_set_addr                     = 0x3C,
		.cfg0_addr                        = 0x200,
		.cfg1_addr                        = 0x204,
		.ctrl_addr                        = 0x208,
		.multi_vcdt_cfg0_addr             = 0x2DC,
		.err_recovery_cfg0_addr           = 0x2D0,
		.err_recovery_cfg1_addr           = 0x2D4,
		.err_recovery_cfg2_addr           = 0x2D8,
		.frm_drop_pattern_addr            = 0,
		.frm_drop_period_addr             = 0,
		.irq_subsample_pattern_addr       = 0,
		.irq_subsample_period_addr        = 0,
		.hcrop_addr                       = 0x21C,
		.pix_drop_pattern_addr            = 0,
		.pix_drop_period_addr             = 0,
		.line_drop_pattern_addr           = 0,
		.line_drop_period_addr            = 0,
		.format_measure_cfg0_addr         = 0x270,
		.format_measure_cfg1_addr         = 0x274,
		.format_measure0_addr             = 0x278,
		.format_measure1_addr             = 0x27C,
		.format_measure2_addr             = 0x280,
		.timestamp_curr0_sof_addr         = 0x290,
		.timestamp_curr1_sof_addr         = 0x294,
		.timestamp_prev0_sof_addr         = 0x298,
		.timestamp_prev1_sof_addr         = 0x29C,
		.timestamp_curr0_eof_addr         = 0x2A0,
		.timestamp_curr1_eof_addr         = 0x2A4,
		.timestamp_prev0_eof_addr         = 0x2A8,
		.timestamp_prev1_eof_addr         = 0x2AC,

		/* configurations */
		.resume_frame_boundary            = 1,
		.binning_supported                = 0x1010,
		.crop_v_en_shift_val              = 6,
		.crop_h_en_shift_val              = 5,
		.drop_v_en_shift_val              = 0,
		.drop_h_en_shift_val              = 0,
		.pix_store_en_shift_val           = 7,
		.early_eof_en_shift_val           = 29,
		.bin_h_en_shift_val               = 0,
		.bin_v_en_shift_val               = 0,
		.bin_en_shift_val                 = 2,
		.bin_qcfa_en_shift_val            = 30,
		.format_measure_en_shift_val      = 0,
		.timestamp_en_shift_val           = 1,
		.overflow_ctrl_en                 = 1,
		.overflow_ctrl_mode_val           = 0x8,
		.fatal_err_mask                   = 0x6E004,
		.non_fatal_err_mask               = 0,
};

static struct cam_ife_csid_ver1_path_reg_info
	cam_ife_csid_662_rdi_0_reg_info = {
		.irq_mask_addr                    = 0x44,
		.irq_clear_addr                   = 0x48,
		.irq_set_addr                     = 0x4C,
		.cfg0_addr                        = 0x300,
		.cfg1_addr                        = 0x304,
		.ctrl_addr                        = 0x308,
		.multi_vcdt_cfg0_addr             = 0x3BC,
		.err_recovery_cfg0_addr           = 0x3B0,
		.err_recovery_cfg1_addr           = 0x3B4,
		.err_recovery_cfg2_addr           = 0x3B8,
		.format_measure_cfg0_addr         = 0x370,
		.format_measure_cfg1_addr         = 0x374,
		.format_measure0_addr             = 0x378,
		.format_measure1_addr             = 0x37C,
		.format_measure2_addr             = 0x380,
		.timestamp_curr0_sof_addr         = 0x390,
		.timestamp_curr1_sof_addr         = 0x394,
		.timestamp_curr0_eof_addr         = 0x3A0,
		.timestamp_curr1_eof_addr         = 0x3A4,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_mode_val           = 0x8,
		.packing_fmt_shift_val            = 30,
		.plain_fmt_shift_val              = 10,
		.crop_v_en_shift_val              = 0,
		.crop_h_en_shift_val              = 0,
		.drop_v_en_shift_val              = 0,
		.drop_h_en_shift_val              = 0,
		.early_eof_en_shift_val           = 29,
		.format_measure_en_shift_val      = 1,
		.timestamp_en_shift_val           = 2,
		.ccif_violation_en                = 0,
		.fatal_err_mask                   = 0x6E004,
		.non_fatal_err_mask               = 0,
		.pix_store_en_shift_val           = 0,
		.mipi_pack_supported              = 1,
		.overflow_ctrl_en                 = 1,
};

static struct cam_ife_csid_ver1_path_reg_info
			cam_ife_csid_662_rdi_1_reg_info = {
		.irq_status_addr                  = 0x50,
		.irq_mask_addr                    = 0x54,
		.irq_clear_addr                   = 0x58,
		.irq_set_addr                     = 0x5C,
		.cfg0_addr                        = 0x400,
		.cfg1_addr                        = 0x404,
		.ctrl_addr                        = 0x408,
		.multi_vcdt_cfg0_addr             = 0x4BC,
		.err_recovery_cfg0_addr           = 0x4B0,
		.err_recovery_cfg1_addr           = 0x4B4,
		.err_recovery_cfg2_addr           = 0x4B8,
		.format_measure_cfg0_addr         = 0x470,
		.format_measure_cfg1_addr         = 0x474,
		.format_measure0_addr             = 0x478,
		.format_measure1_addr             = 0x47C,
		.format_measure2_addr             = 0x480,
		.timestamp_curr0_sof_addr         = 0x490,
		.timestamp_curr1_sof_addr         = 0x494,
		.timestamp_curr0_eof_addr         = 0x4A0,
		.timestamp_curr1_eof_addr         = 0x4A4,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_mode_val           = 0x8,
		.packing_fmt_shift_val            = 30,
		.plain_fmt_shift_val              = 10,
		.crop_v_en_shift_val              = 0,
		.crop_h_en_shift_val              = 0,
		.drop_v_en_shift_val              = 0,
		.drop_h_en_shift_val              = 0,
		.early_eof_en_shift_val           = 29,
		.format_measure_en_shift_val      = 1,
		.timestamp_en_shift_val           = 2,
		.ccif_violation_en                = 0,
		.fatal_err_mask                   = 0x6E004,
		.non_fatal_err_mask               = 0,
		.pix_store_en_shift_val           = 0,
		.mipi_pack_supported              = 1,
		.overflow_ctrl_en                 = 1,
};

static struct cam_ife_csid_ver1_path_reg_info
	cam_ife_csid_662_rdi_2_reg_info = {
		.irq_status_addr                  = 0x60,
		.irq_mask_addr                    = 0x64,
		.irq_clear_addr                   = 0x68,
		.irq_set_addr                     = 0x6C,
		.cfg0_addr                        = 0x500,
		.cfg1_addr                        = 0x504,
		.ctrl_addr                        = 0x508,
		.multi_vcdt_cfg0_addr             = 0x5BC,
		.err_recovery_cfg0_addr           = 0x5B0,
		.err_recovery_cfg1_addr           = 0x5B4,
		.err_recovery_cfg2_addr           = 0x5B8,
		.format_measure_cfg0_addr         = 0x570,
		.format_measure_cfg1_addr         = 0x574,
		.format_measure0_addr             = 0x578,
		.format_measure1_addr             = 0x57C,
		.format_measure2_addr             = 0x580,
		.timestamp_curr0_sof_addr         = 0x590,
		.timestamp_curr1_sof_addr         = 0x594,
		.timestamp_curr0_eof_addr         = 0x5A0,
		.timestamp_curr1_eof_addr         = 0x5A4,

		/* configurations */
		.resume_frame_boundary            = 1,
		.overflow_ctrl_mode_val           = 0x8,
		.packing_fmt_shift_val            = 30,
		.plain_fmt_shift_val              = 10,
		.crop_v_en_shift_val              = 0,
		.crop_h_en_shift_val              = 0,
		.drop_v_en_shift_val              = 0,
		.drop_h_en_shift_val              = 0,
		.early_eof_en_shift_val           = 29,
		.format_measure_en_shift_val      = 1,
		.timestamp_en_shift_val           = 2,
		.ccif_violation_en                = 0,
		.fatal_err_mask                   = 0x6E004,
		.non_fatal_err_mask               = 0,
		.pix_store_en_shift_val           = 0,
		.mipi_pack_supported              = 1,
		.overflow_ctrl_en                 = 1,
};

static struct cam_ife_csid_csi2_rx_reg_info
	cam_ife_csid_662_csi2_reg_info = {
		.irq_status_addr                 = 0x20,
		.irq_mask_addr                   = 0x24,
		.irq_clear_addr                  = 0x28,
		.irq_set_addr                    = 0x2C,
		/*CSI2 rx control */
		.cfg0_addr                       = 0x100,
		.cfg1_addr                       = 0x104,
		.capture_ctrl_addr               = 0x108,
		.cap_unmap_long_pkt_hdr_0_addr   = 0x120,
		.cap_unmap_long_pkt_hdr_1_addr   = 0x124,
		.captured_short_pkt_0_addr       = 0x128,
		.captured_short_pkt_1_addr       = 0x12C,
		.captured_long_pkt_0_addr        = 0x130,
		.captured_long_pkt_1_addr        = 0x134,
		.captured_long_pkt_ftr_addr      = 0x138,
		.captured_cphy_pkt_hdr_addr      = 0x13C,
		.lane0_misr_addr                 = 0x150,
		.lane1_misr_addr                 = 0x154,
		.lane2_misr_addr                 = 0x158,
		.lane3_misr_addr                 = 0x15C,
		.total_pkts_rcvd_addr            = 0x160,
		.stats_ecc_addr                  = 0x164,
		.total_crc_err_addr              = 0x168,
		.de_scramble_type3_cfg0_addr     = 0x170,
		.de_scramble_type3_cfg1_addr     = 0x174,
		.de_scramble_type2_cfg0_addr     = 0x178,
		.de_scramble_type2_cfg1_addr     = 0x17C,
		.de_scramble_type1_cfg0_addr     = 0x180,
		.de_scramble_type1_cfg1_addr     = 0x184,
		.de_scramble_type0_cfg0_addr     = 0x188,
		.de_scramble_type0_cfg1_addr     = 0x18C,

		.rst_done_shift_val              = 27,
		.irq_mask_all                    = 0xFFFFFFF,
		.misr_enable_shift_val           = 6,
		.vc_mode_shift_val               = 2,
		.capture_long_pkt_en_shift       = 0,
		.capture_short_pkt_en_shift      = 1,
		.capture_cphy_pkt_en_shift       = 2,
		.capture_long_pkt_dt_shift       = 4,
		.capture_long_pkt_vc_shift       = 10,
		.capture_short_pkt_vc_shift      = 15,
		.capture_cphy_pkt_dt_shift       = 20,
		.capture_cphy_pkt_vc_shift       = 26,
		.phy_num_mask                    = 0x3,
		.vc_mask                         = 0x7C00000,
		.dt_mask                         = 0x3f0000,
		.wc_mask                         = 0xffff,
		.vc_shift                        = 0x16,
		.dt_shift                        = 0x10,
		.wc_shift                        = 0,
		.calc_crc_mask                   = 0xffff0000,
		.expected_crc_mask               = 0xffff,
		.calc_crc_shift                  = 0x10,
		.ecc_correction_shift_en         = 0,
		.lane_num_shift                  = 0,
		.lane_cfg_shift                  = 4,
		.phy_type_shift                  = 24,
		.phy_num_shift                   = 20,
		.tpg_mux_en_shift                = 0,
		.tpg_num_sel_shift               = 0,
		.phy_bist_shift_en               = 0,
		.epd_mode_shift_en               = 0,
		.eotp_shift_en                   = 0,
		.dyn_sensor_switch_shift_en      = 0,
		.rup_aup_latch_shift             = 0,
		.rup_aup_latch_supported         = false,
		.long_pkt_strobe_rst_shift       = 1,
		.short_pkt_strobe_rst_shift      = 2,
		.cphy_pkt_strobe_rst_shift       = 3,
		.unmapped_pkt_strobe_rst_shift   = 4,
		.fatal_err_mask                  = 0x187A000,
		.part_fatal_err_mask             = 0x181800,
		.non_fatal_err_mask              = 0x200000,
};

static struct cam_ife_csid_ver1_common_reg_info
	cam_ife_csid_662_cmn_reg_info = {
		.hw_version_addr                         = 0x0,
		.cfg0_addr                               = 0x4,
		.ctrl_addr                               = 0x8,
		.top_irq_status_addr                     = 0x70,
		.top_irq_mask_addr                       = 0x74,
		.top_irq_clear_addr                      = 0x78,
		.top_irq_set_addr                        = 0x7c,
		.irq_cmd_addr                            = 0x80,

		/*configurations */
		.major_version                           = 6,
		.minor_version                           = 6,
		.version_incr                            = 2,
		.num_rdis                                = 3,
		.num_pix                                 = 1,
		.num_ppp                                 = 0,
		.rst_done_shift_val                      = 1,
		.path_en_shift_val                       = 31,
		.dt_id_shift_val                         = 27,
		.vc_shift_val                            = 22,
		.dt_shift_val                            = 16,
		.crop_shift_val                          = 16,
		.decode_format_shift_val                 = 12,
		.multi_vcdt_vc1_shift_val                = 2,
		.multi_vcdt_dt1_shift_val                = 7,
		.multi_vcdt_ts_combo_en_shift_val        = 13,
		.multi_vcdt_en_shift_val                 = 0,
		.timestamp_stb_sel_shift_val             = 0,
		.early_eof_supported                     = 1,
		.multi_vcdt_supported                    = 0,
		.measure_en_hbi_vbi_cnt_mask             = 0xc,
		.measure_pixel_line_en_mask              = 0x3,
		.crop_pix_start_mask                     = 0x3fff,
		.crop_pix_end_mask                       = 0xffff,
		.crop_line_start_mask                    = 0x3fff,
		.crop_line_end_mask                      = 0xffff,
		.drop_supported                          = 0,
		.ipp_irq_mask_all                        = 0x7FFB,
		.rdi_irq_mask_all                        = 0x7FFB,
		.timestamp_strobe_val                    = 0x2,
		.global_reset                            = 0,
		.aup_rup_supported                       = 0,
		.num_perf_cntrs                          = 0,
		.num_dt_supported                        = 1,
		.format_measure_height_mask_val          = 0xFFFF,
		.format_measure_height_shift_val         = 0x10,
		.format_measure_width_mask_val           = 0xFFFF,
		.format_measure_width_shift_val          = 0x0,
};

static struct cam_ife_csid_ver1_reg_info cam_ife_csid_662_reg_info = {
	.cmn_reg          = &cam_ife_csid_662_cmn_reg_info,
	.csi2_reg         = &cam_ife_csid_662_csi2_reg_info,
	.ipp_reg          = &cam_ife_csid_662_ipp_reg_info,
	.ppp_reg          = NULL,
	.rdi_reg = {
		&cam_ife_csid_662_rdi_0_reg_info,
		&cam_ife_csid_662_rdi_1_reg_info,
		&cam_ife_csid_662_rdi_2_reg_info,
		NULL,
		},
	.tpg_reg = NULL,
	.csid_cust_node_map = {0, 0},
};
#endif /*_CAM_IFE_CSID_662_H_ */
